name: CI Live

on:
  push:
    branches:
      - master
    tags-ignore:
      - rel-*

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  call_build:
    uses: ./.github/workflows/ci_shared.yaml
    with:
      client_target: live
    secrets: inherit