name: CD MacroQuest [EMU]   

on:
  push:
    branches: [ "emu" ]
  pull_request:
    branches: [ "emu" ]

jobs:
  s1:
    uses: ./.github/workflows/emu_shared.yaml
    with:
      client_target: emu
    secrets: inherit

  publish:
    name: Publish Macroquest with plugins
    runs-on: [windows-2022]
    needs: s1
    steps:
      - name: Restore cache of build artifacts
        uses: actions/cache/restore@v3
        id: restore-cache-build
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-artifacts-${{ env.platform }}

      - name: Upload build artefact
        uses: actions/upload-artifact@v3
        with:
          name: MacroQuest
          path: ${{ github.workspace }}\build\bin\${{env.config}}
    
      - name: Cleanup artifacts cache
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge

          cacheKey=${{ runner.os }}-artifacts-${{ env.platform }}

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting source cache..."
          gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        