name: CD MacroQuest [EMU]   

on:
  push:
    branches: [ "emu" ]
  pull_request:
    branches: [ "emu" ]

jobs:
  call_build:
    uses: ./.github/workflows/emu_shared.yaml
    with:
      client_target: emu
      deploy_target: test
    secrets: inherit

        